version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    ports:
      - "5050:80" # Expose pgAdmin on port 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123

volumes:
  postgres_data:
